//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub is_group: i8,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_members::Entity")]
    ChatMembers,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
}

impl Related<super::chat_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatMembers.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::chat_members::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::chat_members::Relation::Chats.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
