//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;

pub mod blocked_users;
pub mod chat_members;
pub mod chats;
pub mod friend_requests;
pub mod friends;
pub mod messages;
pub mod sea_orm_active_enums;
pub mod users;
