//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::chat_members::Entity as ChatMembers;
pub use super::chats::Entity as Chats;
pub use super::friends::Entity as Friends;
pub use super::messages::Entity as Messages;
pub use super::users::Entity as Users;
