on:
  push:
    branches:
      - main
      - brendonnewt/cicd

jobs:
  build-and-deploy:
    name: Build & Deploy to main
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3

      - name: Pre-Clean
        run: |
          docker image prune -af

      - name: Set IP Address
        run: |
          echo "Setting IP Address to PROD"
        # echo "NEXT_PUBLIC_API_URL=http://woofadoption.homes:8080" > pet-adoption-frontend/.env.production
        # echo "cors.allowed-origin=http://woofadoption.homes:80" > pet-adoption-api/src/main/resources/application.properties

      - name: Build
        run: |
          docker compose -f Docker/ci.docker-compose.yml build

      - name: Deploy
        run: |
          docker compose -f Docker/ci.docker-compose.yml down
          docker compose -f Docker/ci.docker-compose.yml up -d --build

      - name: Post-Clean
        run: |
          docker image prune -af
