on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    name: Build & Deploy to main
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3

      - name: Pre-Clean
        run: |
          docker image prune -af

      - name: Build
        working-directory: final-project-group2_s25
        run: |
          docker compose -f docker/ci.docker-compose.yml build

      - name: Deploy
        working-directory: final-project-group2_s25
        run: |
          docker compose -f docker/ci.docker-compose.yml down
          docker compose -f docker/ci.docker-compose.yml up -d --build

      - name: Post-Clean
        run: |
          docker image prune -af
