on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy to main
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3

      - name: Pre-Clean
        run: |
          docker image prune -af

      - name: Set up env
        run: |
          echo "SECRET=${{ secrets.SECRET }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV


      - name: Build
        run: |
          docker compose -f docker/ci.docker-compose.yml build

      - name: Deploy
        run: |
          docker compose -f docker/ci.docker-compose.yml down
          docker compose -f docker/ci.docker-compose.yml up -d --build

      - name: Post-Clean
        run: |
          docker image prune -af
